In [45]:
# Importando dataset e visualizando as primeiras 3 linhas
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori , association_rules
import pandas as pd
df = pd.read_csv(r'C:\Users\walte\Documents\Aquivos_Walter\Universidade dos dados\Python + Power BI\Superstore\Superstore.csv' ,  encoding='windows-1252')
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [46]:
df_reduzido = df.loc[:, ["Order ID","Product ID"]]
df_reduzido.head()

         Order ID       Product ID
0  CA-2013-152156  FUR-BO-10001798
1  CA-2013-152156  FUR-CH-10000454
2  CA-2013-138688  OFF-LA-10000240
3  US-2012-108966  FUR-TA-10000577
4  US-2012-108966  OFF-ST-10000760

In [47]:
# Agrupando pelo Order ID e agregando os Product ID em uma lista
df_grouped = df_reduzido.groupby('Order ID')['Product ID'].apply(list).reset_index()
df_grouped.head()

         Order ID                          Product ID
0  CA-2011-100006                   [TEC-PH-10002075]
1  CA-2011-100090  [FUR-TA-10003715, OFF-BI-10001597]
2  CA-2011-100293                   [OFF-PA-10000176]
3  CA-2011-100328                   [OFF-BI-10000343]
4  CA-2011-100363  [OFF-FA-10000611, OFF-PA-10004733]

In [57]:
lista_produtos = df_grouped['Product ID'].tolist()
te = TransactionEncoder()
te_ary = te.fit(df_grouped['Product ID']).transform(df_grouped['Product ID'])
df2 = pd.DataFrame(te_ary, columns = te.columns_)

df2 = df2.astype(int)

df2

,FUR-BO-10000112,FUR-BO-10000330,FUR-BO-10000362,FUR-BO-10000468,FUR-BO-10000711,FUR-BO-10000780,FUR-BO-10001337,FUR-BO-10001519,FUR-BO-10001567,FUR-BO-10001601,...,TEC-PH-10004833,TEC-PH-10004875,TEC-PH-10004896,TEC-PH-10004897,TEC-PH-10004908,TEC-PH-10004912,TEC-PH-10004922,TEC-PH-10004924,TEC-PH-10004959,TEC-PH-10004977
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5006,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5007,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5008,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
frequent_itemsets =  apriori(df2 , min_support = 0.01 , use_colnames= True)

frequent_itemsets

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [56]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Criando um DataFrame de exemplo com transaÃ§Ãµes
data = {
    'Leite': [1, 1, 0, 1, 0],
    'PÃ£o': [1, 1, 1, 0, 1],
    'Manteiga': [0, 1, 1, 1, 0],
    'Cerveja': [0, 0, 1, 1, 1],
    'CafÃ©': [1, 0, 0, 1, 1]
}
df = pd.DataFrame(data)

# Rodando o algoritmo Apriori para encontrar conjuntos frequentes
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

# Gerando as regras de associaÃ§Ã£o
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Exibindo os conjuntos frequentes
print("Conjuntos frequentes:")
print(frequent_itemsets)

# Exibindo as regras de associaÃ§Ã£o
print("\nRegras de associaÃ§Ã£o:")
print(rules)

Conjuntos frequentes:
   support    itemsets
0      0.6     (Leite)
1      0.8       (PÃ£o)
2      0.6  (Manteiga)
3      0.6   (Cerveja)
4      0.6      (CafÃ©)

Regras de associaÃ§Ã£o:
Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []

In [ ]:
print(true_values)